default['appdynamics']['tempdir'] = "C:\\Windows\\Temp"
default['appdynamics']['installdir'] = "C:\\AppDynamics"
default['appdynamics']['agent']['logdir'] = "C:\\AppDynamics\\DotNetAgent\\Logs"
default['appdynamics']['controller']['host'] = "172.16.10.81"
default['appdynamics']['controller']['port'] = "8090"
default['appdynamics']['application'] = "App123"
default['appdynamics']['tier'] = "Tier123"
default['appdynamics']['node'] = "Node123"